import {vocabulary} from './data/vocab.js';
import {grammar} from './data/grammar.js';
import {quizzes} from './data/quizzes.js';
import {API_BASE} from './config.js';

const state={view:'home',lesson:1,search:'',flashIndex:0,quizIndex:0,quizScore:0,answered:false,flipped:false,user:null};
const app=document.querySelector('#app');
const byLesson=(arr,n)=>arr.filter(x=>x.lesson===n);
function nav(){return `<header class="top"><div class="nav"><div class="brand">Minna <span>N5</span> Hub</div><div class="navlinks">${[['home','Trang chủ'],['lessons','25 bài học'],['vocab','Từ vựng'],['grammar','Ngữ pháp'],['flash','Flashcard'],['quiz','Quiz']].map(([k,t])=>`<button class="${state.view===k?'active':''}" data-view="${k}">${t}</button>`).join('')}</div><button class="btn" id="accountBtn">${state.user?state.user.email:'Đăng nhập'}</button></div></header>`}
function lessons(){return `<div class="grid">${Array.from({length:25},(_,i)=>i+1).map(n=>`<div class="panel lesson" data-lesson="${n}"><span class="pill">Bài ${n}</span><h3>Minna no Nihongo N5</h3><p class="muted">${byLesson(vocabulary,n).length} mục từ vựng · ${byLesson(grammar,n)[0]?.items.length||0} điểm ngữ pháp</p></div>`).join('')}</div>`}
function home(){return `<div class="hero"><section class="panel"><span class="pill">JLPT N5 · Bài 1–25</span><h1>Học tiếng Nhật theo lộ trình rõ ràng.</h1><p class="muted">Từ vựng, ngữ pháp, flashcard, bài tập điền chỗ trống và quiz theo mức độ. Nội dung dữ liệu được chuẩn hóa từ tài liệu bạn đã cung cấp.</p><div class="stats"><div class="stat"><b>25</b><span>bài học</span></div><div class="stat"><b>${vocabulary.length}+</b><span>mục từ vựng trích xuất</span></div><div class="stat"><b>${grammar.reduce((s,x)=>s+x.items.length,0)}</b><span>mẫu ngữ pháp</span></div></div><div class="toolbar"><button class="btn primary" data-view="lessons">Bắt đầu học</button><button class="btn" data-view="flash">Ôn flashcard</button></div></section><aside class="panel"><h3>Tiến độ cá nhân</h3><div class="progress"><div style="width:18%"></div></div><p class="muted">Bản GitHub Pages này lưu tiến độ cơ bản trong trình duyệt. Khi nối backend, tiến độ có thể lưu theo tài khoản.</p><h4>Học mỗi ngày</h4><p>10–20 từ → 1 nhóm ngữ pháp → 10 câu quiz.</p></aside></div><h2 style="margin-top:28px">Chọn bài học</h2>${lessons()}`}
function vocabView(){let data=vocabulary.filter(x=>(x.lesson===state.lesson||!state.lesson)&&(`${x.jp} ${x.romaji} ${x.vi}`).toLowerCase().includes(state.search.toLowerCase()));return `<section class="panel"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0">Từ vựng</h2><p class="muted">${state.lesson?'Bài '+state.lesson:'Tất cả bài 1–25'}</p></div><select class="input" id="lessonSelect" style="width:auto;margin:0"><option value="0">Tất cả bài</option>${Array.from({length:25},(_,i)=>`<option ${state.lesson===i+1?'selected':''} value="${i+1}">Bài ${i+1}</option>`).join('')}</select></div><input class="search" id="search" value="${state.search}" placeholder="Tìm tiếng Nhật, romaji hoặc tiếng Việt…"/><div class="tablewrap"><table class="table"><thead><tr><th>Bài</th><th>Chữ Nhật</th><th>Romaji</th><th>Nghĩa tiếng Việt</th></tr></thead><tbody>${data.map(x=>`<tr><td><span class="tag">${x.lesson}</span></td><td class="jp jpword">${x.jp}</td><td>${x.romaji}</td><td>${x.vi}</td></tr>`).join('')}</tbody></table></div></section>`}
function grammarView(){let data=state.lesson?grammar.filter(x=>x.lesson===state.lesson):grammar;return `<section class="panel"><div class="toolbar"><select class="input" id="grammarLesson" style="width:auto;margin:0"><option value="0">Tất cả bài</option>${Array.from({length:25},(_,i)=>`<option ${state.lesson===i+1?'selected':''} value="${i+1}">Bài ${i+1}</option>`).join('')}</select></div>${data.map(g=>`<article style="margin:18px 0"><h3>Bài ${g.lesson}</h3>${g.items.map(it=>`<div style="padding:13px 0;border-top:1px solid #edf0f5"><div class="jp" style="font-size:20px;font-weight:700">${it.pattern}</div><div class="muted">${it.meaning}</div></div>`).join('')}</article>`).join('')}</section>`}
function flashView(){let data=byLesson(vocabulary,state.lesson); if(!data.length)data= vocabulary.slice(0,30); let w=data[state.flashIndex%data.length];return `<section class="panel"><div class="toolbar"><select class="input" id="flashLesson" style="width:auto;margin:0"><option value="0">Bài 1 mẫu</option>${Array.from({length:25},(_,i)=>`<option ${state.lesson===i+1?'selected':''} value="${i+1}">Bài ${i+1}</option>`).join('')}</select><span class="pill">${state.flashIndex%data.length+1}/${data.length}</span></div><div class="flash-area"><div class="flash ${state.flipped?'flipped':''}" id="flashcard"><div class="flash-inner"><div class="face"><div class="big jp">${w.jp}</div><p>Nhấn để lật thẻ</p></div><div class="face back"><div class="big" style="font-size:34px">${w.vi}</div><p>${w.romaji}</p></div></div></div></div><div class="toolbar" style="justify-content:center"><button class="btn" id="prevFlash">← Trước</button><button class="btn primary" id="nextFlash">Tiếp →</button></div></section>`}
function quizView(){let q=quizzes[state.quizIndex%quizzes.length];let opts=[...q.options]; // add distractors from nearby answers
if(opts.length<3){for(const z of quizzes){if(z.id!==q.id && z.answer && !opts.includes(z.answer)){opts.push(z.answer);if(opts.length===3)break}}}
return `<section class="panel"><div class="toolbar"><span class="pill">Bài ${q.lesson}</span><span class="pill">${q.difficulty}</span><span class="pill">Điểm: ${state.quizScore}</span></div><div class="progress"><div style="width:${((state.quizIndex%20)+1)/20*100}%"></div></div><div class="quizq">${q.question}</div><div class="options">${opts.map((o,i)=>`<button class="option" data-opt="${encodeURIComponent(o)}">${o}</button>`).join('')}</div><div id="quizFeedback" style="margin-top:15px"></div><div class="toolbar"><button class="btn" id="nextQuiz">Câu tiếp theo →</button></div></section>`}
function authModal(){return `<div class="modal" id="modal"><div class="panel"><h2>Tài khoản</h2><div class="toolbar"><button class="btn primary" id="tabLogin">Đăng nhập</button><button class="btn" id="tabRegister">Đăng ký</button></div><div id="authForm"><label>Email</label><input class="input" id="email" type="email" placeholder="ban@gmail.com"><label>Mật khẩu</label><input class="input" id="password" type="password" placeholder="••••••••"><button class="btn primary" id="login">Đăng nhập</button><button class="btn" id="forgot">Quên mật khẩu / nhận mã</button></div><button class="btn" id="closeModal" style="margin-top:12px">Đóng</button><div id="authMsg" class="muted" style="margin-top:10px"></div></div></div>`}
async function api(path,body){const r=await fetch(`${API_BASE}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let j={};try{j=await r.json()}catch{};if(!r.ok)throw new Error(j.error||'Có lỗi xảy ra');return j}
function authBind(){
 const modal=document.querySelector('#modal'), msg=document.querySelector('#authMsg');
 document.querySelector('#closeModal').onclick=()=>modal.remove();
 const showRegister=()=>{document.querySelector('#authForm').innerHTML=`<label>Email</label><input class="input" id="email" type="email" placeholder="ban@gmail.com"><label>Mật khẩu</label><input class="input" id="password" type="password" placeholder="Tối thiểu 8 ký tự"><button class="btn primary" id="register">Tạo tài khoản</button>`;document.querySelector('#register').onclick=async()=>{try{await api('/auth/register',{email:document.querySelector('#email').value,password:document.querySelector('#password').value});msg.textContent='Đăng ký thành công. Bạn có thể đăng nhập.'}catch(e){msg.textContent=e.message}}};
 const showLogin=()=>{document.querySelector('#authForm').innerHTML=`<label>Email</label><input class="input" id="email" type="email" placeholder="ban@gmail.com"><label>Mật khẩu</label><input class="input" id="password" type="password"><button class="btn primary" id="login">Đăng nhập</button><button class="btn" id="forgot">Quên mật khẩu / nhận mã</button>`;document.querySelector('#login').onclick=async()=>{try{const j=await api('/auth/login',{email:document.querySelector('#email').value,password:document.querySelector('#password').value});localStorage.setItem('n5_token',j.token);state.user={email:j.email};msg.textContent='Đăng nhập thành công.';setTimeout(()=>modal.remove(),500)}catch(e){msg.textContent=e.message}};document.querySelector('#forgot').onclick=showForgot};
 const showForgot=()=>{document.querySelector('#authForm').innerHTML=`<label>Email Gmail</label><input class="input" id="email" type="email" placeholder="ban@gmail.com"><button class="btn primary" id="sendCode">Gửi mã 6 số</button><div id="otpStep" style="margin-top:12px"></div>`;document.querySelector('#sendCode').onclick=async()=>{try{const email=document.querySelector('#email').value;await api('/auth/send-reset-code',{email});document.querySelector('#otpStep').innerHTML=`<input class="input" id="code" placeholder="Mã 6 số"><input class="input" id="newPass" type="password" placeholder="Mật khẩu mới"><button class="btn primary" id="resetPass">Đặt lại mật khẩu</button>`;document.querySelector('#resetPass').onclick=async()=>{try{await api('/auth/reset-password',{email,code:document.querySelector('#code').value,newPassword:document.querySelector('#newPass').value});msg.textContent='Đổi mật khẩu thành công. Hãy đăng nhập lại.';showLogin()}catch(e){msg.textContent=e.message}}}catch(e){msg.textContent=e.message}}};
 document.querySelector('#tabLogin').onclick=showLogin;document.querySelector('#tabRegister').onclick=showRegister;showLogin();
}
function render(){let body=state.view==='home'?home():state.view==='lessons'?`<h2>25 bài học</h2>${lessons()}`:state.view==='vocab'?vocabView():state.view==='grammar'?grammarView():state.view==='flash'?flashView():quizView();app.innerHTML=nav()+`<main class="container">${body}<div class="footer">Minna N5 Hub · GitHub-ready · Dữ liệu học tập theo tài liệu đã cung cấp</div></main>`;bind();}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view; if(state.view==='vocab'||state.view==='grammar'||state.view==='flash')state.lesson=state.lesson||1;render()});document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{state.lesson=+b.dataset.lesson;state.view='vocab';render()});const s=document.querySelector('#search');if(s)s.oninput=e=>{state.search=e.target.value;render()};const ls=document.querySelector('#lessonSelect');if(ls)ls.onchange=e=>{state.lesson=+e.target.value||0;render()};const gl=document.querySelector('#grammarLesson');if(gl)gl.onchange=e=>{state.lesson=+e.target.value||0;render()};const fl=document.querySelector('#flashLesson');if(fl)fl.onchange=e=>{state.lesson=+e.target.value||1;state.flashIndex=0;state.flipped=false;render()};const card=document.querySelector('#flashcard');if(card)card.onclick=()=>{state.flipped=!state.flipped;render()};const nx=document.querySelector('#nextFlash');if(nx)nx.onclick=()=>{state.flashIndex++;state.flipped=false;render()};const pv=document.querySelector('#prevFlash');if(pv)pv.onclick=()=>{state.flashIndex=Math.max(0,state.flashIndex-1);state.flipped=false;render()};const nq=document.querySelector('#nextQuiz');if(nq)nq.onclick=()=>{state.quizIndex++;state.answered=false;render()};document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{if(state.answered)return;state.answered=true;const ans=decodeURIComponent(b.dataset.opt);const q=quizzes[state.quizIndex%quizzes.length];if(ans===q.answer){state.quizScore++;b.classList.add('correct');}else{b.classList.add('wrong')}const fb=document.querySelector('#quizFeedback');fb.innerHTML=`<div class="panel" style="padding:12px">Đáp án: <b>${q.answer}</b></div>`});const ab=document.querySelector('#accountBtn');if(ab)ab.onclick=()=>{app.insertAdjacentHTML('beforeend',authModal());authBind()}}
render();
